# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0002_auto_20170514_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipOfEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_direction', models.CharField(choices=[('reason', 'reason'), ('result', 'result')], max_length=6)),
                ('child_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_event', to='rest_server.Event')),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_event', to='rest_server.Event')),
            ],
        ),
    ]
